Repository codeit-part3-team4-WINE/WINE, pull requests merged in 2025-06, with the labels that each got.

#15 파일 네이밍 컨벤션 수정
  src/app/global-error.tsx
  src/app/layout.tsx
  src/app/login/error.tsx
  src/app/myprofile/error.tsx
  src/app/signup/error.tsx
  src/app/wines/[wineId]/error.tsx
  src/app/wines/error.tsx
  src/components/ErrorFallback.tsx
  src/libs/queryProvider.tsx
  src/types/error.ts
Labels: 🐞 bug

#24 Button 공통 컴포넌트 개발 & 디자인 시스템 페이지
  src/app/assets/icons/loader-circle.tsx
  src/app/design-system/layout.tsx
  src/app/design-system/page.tsx
  src/app/design-system/ui-button/page.tsx
  src/app/design-system/ui-icon/page.tsx
  src/components/Button.tsx
  src/constants/button.js
  src/types/icon.ts
Labels: 🎨 design, 🧩 feature

#23 Feat/12 ProfileImg 공통 컴포넌트 구현
  pnpm-lock.yaml
  src/app/assets/svgs/profile-default.svg
  src/app/assets/svgs/profile-select-overlay.svg
  src/app/design-system/page.tsx
  src/app/design-system/ui-profileImg/mock-image/mock-img.png
  src/app/design-system/ui-profileImg/page.tsx
  src/components/ProfileImg.tsx
Labels: 🧩 feature

#27 Feat/18 Dropdown 공통 컴포넌트 구현
  src/app/design-system/ui-dropdown/page.tsx
  src/components/Dropdown/Dropdown.Item.tsx
  src/components/Dropdown/Dropdown.Menu.tsx
  src/components/Dropdown/Dropdown.Trigger.tsx
  src/components/Dropdown/Dropdown.tsx
  src/components/Dropdown/DropdownContext.ts
  src/components/Dropdown/index.ts
Labels: 🧩 feature

#29 헤더 공통컴포넌트 UI 구현
  src/app/assets/icons/wine-logo.tsx
  src/app/layout.tsx
  src/components/Header.tsx
Labels: 🎨 design

#38 별점 공통 컴포넌트 개발
  src/app/assets/icons/star.tsx
  src/app/design-system/page.tsx
  src/app/design-system/ui-rating-summary/page.tsx
  src/components/RatingSummary.tsx
Labels: 🎨 design

#50 Radio 컴포넌트 개발
  src/app/design-system/page.tsx
  src/app/design-system/ui-radio/page.tsx
  src/app/wines/components/Radio.tsx
  src/app/wines/components/dummy
Labels: 🎨 design, 🧩 feature

#57 Recommended Wine Item 컴포넌트 개발
  src/app/assets/images/dummy_wine_image.png
  src/app/design-system/page.tsx
  src/app/design-system/ui-recommend-wine-item/page.tsx
  src/app/globals.css
  src/app/wines/components/RecommendedWineItem.tsx
  src/components/RatingSummary.tsx
Labels: 🎨 design

#66 Feat/49 Myprofile 페이지 - ProfileSection & Tab 컴포넌트 구현
  src/app/myprofile/components/ProfileSection/ChangeBtn.tsx
  src/app/myprofile/components/ProfileSection/ProfileSection.tsx
  src/app/myprofile/components/Tab.tsx
  src/app/myprofile/components/dummy
Labels: 🎨 design

#59 [#55] feat: 리뷰 카드 작성
  src/app/assets/icons/heart.tsx
  src/app/wines/[wineId]/components/ReviewCard.tsx
  src/app/wines/[wineId]/page.tsx
  src/libs/formmatToTimeago.tsx
Labels: 🎨 design

#83 [#76] feat: 와인 상세 페이지 UI
  src/app/assets/icons/exclamation-mark.tsx
  src/app/design-system/ui-wine-details/page.tsx
  src/app/wines/[wineId]/components/Nothing.tsx
  src/app/wines/[wineId]/components/ReviewCard.tsx
  src/app/wines/[wineId]/components/ReviewRating/ReviewOverview.tsx
  src/app/wines/[wineId]/page.tsx
  src/components/Badge/StarBadge.tsx
  src/components/WineInfo.tsx
Labels: 🎨 design

#86 [#82] feat: 와인 향 분석 컴포넌트
  src/app/design-system/page.tsx
  src/app/design-system/ui-aroma-analysis/page.tsx
  src/app/wines/[wineId]/AromaAnalysis/AromaAnalysis.tsx
  src/app/wines/[wineId]/AromaAnalysis/AromaCard.tsx
  src/app/wines/[wineId]/AromaAnalysis/AromaIcon.tsx
  src/app/wines/[wineId]/AromaAnalysis/types.ts
  src/app/wines/[wineId]/AromaAnalysis/utils.ts
  src/app/wines/[wineId]/dummy.ts
Labels: 🎨 design, 🧩 feature

#85 Feat/81 프로필 변경 모달 Form UI 및 기본 동작 구현
  src/app/design-system/ui-inputfile/page.tsx
  src/app/design-system/ui-profile-change/page.tsx
  src/app/myprofile/components/ProfileChangeModal/ProfileChangeForm.tsx
  src/app/myprofile/components/ProfileChangeModal/ProfileChangeModal.tsx
  src/components/Inputs/InputFile.tsx
Labels: 🎨 design, 🧩 feature

#39 Modal 공통 컴포넌트 개발
  src/app/assets/icons/close.tsx
  src/app/design-system/page.tsx
  src/app/design-system/ui-icon/page.tsx
  src/app/design-system/ui-modal/page.tsx
  src/app/globals.css
  src/app/layout.tsx
  src/components/Modal/Modal.tsx
  src/components/Modal/ModalBody.tsx
  src/components/Modal/ModalClose.tsx
  src/components/Modal/ModalContent.tsx
  src/components/Modal/ModalContext.tsx
  src/components/Modal/ModalFooter.tsx
  src/components/Modal/ModalHeader.tsx
  src/components/Modal/ModalTitle.tsx
  src/components/Modal/ModalTrigger.tsx
  src/components/Modal/index.ts
  src/components/Modal/types.ts
  src/components/Slot.tsx
Labels: 🧩 feature

#80 Feat/73 Myprofile 페이지 전체 UI구현 및 중첩 라우팅 적용을 통한 Tab 네비게이션 Bar 구현
  src/app/myprofile/(tab)/favorites/page.tsx
  src/app/myprofile/(tab)/reviews/page.tsx
  src/app/myprofile/(tab)/wines/page.tsx
  src/app/myprofile/components/Card/ReviewCard.tsx
  src/app/myprofile/components/Card/WineCard.tsx
  src/app/myprofile/components/ProfileSection/ProfileSection.tsx
  src/app/myprofile/components/Tab.tsx
  src/app/myprofile/components/mock/mock-data.ts
  src/app/myprofile/components/mock/profile1.png
  src/app/myprofile/components/mock/wine-dummy.png
  src/app/myprofile/layout.tsx
  src/app/myprofile/page.tsx
Labels: 🎨 design

#88 와인 목록 페이지 UI 구현
  src/app/design-system/ui-dual-range-slider/page.tsx
  src/app/layout.tsx
  src/app/wines/components/DualRangeSlider.tsx
  src/app/wines/components/PriceRangeSlider.tsx
  src/app/wines/components/ReviewActionButton.tsx
  src/app/wines/components/WineFilterSidebar.tsx
  src/app/wines/components/WineListCard.tsx
  src/app/wines/components/WineListContainer.tsx
  src/app/wines/components/WineRecommendationSection.tsx
  src/app/wines/components/WineSearchBar.tsx
  src/app/wines/page.tsx
  src/components/Footer.tsx
  src/components/Header.tsx
  src/components/Inputs/SearchInput.tsx
Labels: 🎨 design

#92 global.css의 오타 수정
  src/app/design-system/ui-modal/page.tsx
  src/app/globals.css
Labels: 🐞 bug

#103 [#84] feat: 맛 분석 컴포넌트 구현
  src/app/design-system/page.tsx
  src/app/design-system/ui-aroma-analysis/page.tsx
  src/app/design-system/ui-wine-details/page.tsx
  src/app/page.tsx
  src/app/wines/[wineId]/components/AromaAnalysis/AromaAnalysis.tsx
  src/app/wines/[wineId]/components/AromaAnalysis/AromaCard.tsx
  src/app/wines/[wineId]/components/AromaAnalysis/AromaIcon.tsx
  src/app/wines/[wineId]/components/AromaAnalysis/types.ts
  src/app/wines/[wineId]/components/AromaAnalysis/utils.ts
  src/app/wines/[wineId]/components/flavorAnalysis/FlavorAnalysis.tsx
  src/app/wines/[wineId]/components/flavorAnalysis/utils.ts
  src/app/wines/[wineId]/dummy.ts
  src/components/Footer.tsx
  src/components/InputRange.tsx
Labels: 🎨 design, 🧩 feature

#104 [#95] refactor: 와인 상세페이지 2차 QA 반영
  src/app/wines/[wineId]/components/ReviewCard.tsx
  src/app/wines/[wineId]/components/ReviewRating/ReviewOverview.tsx
  src/components/Badge/Badge.tsx
  src/components/InputRange.tsx
Labels: 🛠️ refactor

#102 Refactor/93 2차 QA 피드백 반영
  src/app/myprofile/(tab)/favorites/page.tsx
  src/app/myprofile/(tab)/reviews/page.tsx
  src/app/myprofile/(tab)/wines/page.tsx
  src/app/myprofile/components/Card/ReviewCard.tsx
  src/app/myprofile/components/Card/WineCard.tsx
  src/app/myprofile/components/ProfileChangeModal/ProfileChangeForm.tsx
  src/app/myprofile/components/Tab.tsx
  src/components/Dropdown/Dropdown.Menu.tsx
Labels: 🛠️ refactor

#100 2차 QA 반영
  src/app/wines/components/WineFilterSidebar.tsx
Labels: 🐞 bug, 🎨 design

#112 와인 검색 필터링 모달 및 필터링 상태 관리
  src/app/design-system/ui-dual-range-slider/page.tsx
  src/app/design-system/ui-radio/page.tsx
  src/app/wines/components/DualRangeSlider.tsx
  src/app/wines/components/Filter.tsx
  src/app/wines/components/PriceRangeSlider.tsx
  src/app/wines/components/Radio.tsx
  src/app/wines/components/WineFilterSidebar.tsx
  src/app/wines/components/WineSearchBar.tsx
  src/app/wines/components/WineSearchSection.tsx
  src/app/wines/page.tsx
  src/components/Modal/ModalContent.tsx
Labels: 🧩 feature, 🛠️ refactor

#107 로그인/회원가입 페이지 UI/검증로직
  src/apis/privateInstance.ts
  src/apis/privateServerInstance.ts
  src/app/DynamicLayout.tsx
  src/app/api/auth/logout/route.ts
  src/app/api/users/me/route.ts
  src/app/api/wines/[id]/route.ts
  src/app/authlogictest/page.tsx
  src/app/layout.tsx
  src/app/login/action.ts
  src/app/login/components/LoginForm.tsx
  src/app/signup/action.ts
  src/app/signup/components/SignupForm.tsx
  src/components/Inputs/InputPair.tsx
  src/types/error.ts
  src/utils/validateInput.ts
Labels: 🧩 feature

#120 [#119] feat: liked function add
  src/app/api/wines/[id]/like/route.ts
  src/app/api/wines/[id]/route.ts
  src/app/assets/icons/chevron-arrow.tsx
  src/app/wines/[wineId]/components/ReviewCard.tsx
  src/app/wines/[wineId]/page.tsx
  src/types/error.ts
Labels: 📮 api, 🧩 feature

#113 Footer range thumb 리팩토링
  src/app/layout.tsx
  src/components/Footer.tsx
  src/components/InputRange.tsx
  src/components/RangeSlider.tsx
Labels: 🛠️ refactor

#136 3차 QA사항수정/카카오 로그인시 로딩컴포넌트추가
  src/app/layout.tsx
  src/app/login/components/LoginForm.tsx
  src/app/oauth/kakao/components/KakaoLoading.tsx
  src/app/oauth/kakao/page.tsx
  src/app/signup/components/SignupForm.tsx
  src/components/Header.tsx
Labels: 🛠️ refactor

#134 [#128] refactor: 3차 QA 내용 반영 및 무한 스크롤
  src/app/api/wines/[id]/route.ts
  src/app/layout.tsx
  src/app/wines/[wineId]/components/AromaAnalysis/AromaAnalysis.tsx
  src/app/wines/[wineId]/components/Nothing.tsx
  src/app/wines/[wineId]/components/ReviewCard.tsx
  src/app/wines/[wineId]/components/ReviewRating/ReviewRange.tsx
  src/app/wines/[wineId]/components/ReviewRating/ReviewRangeGroup.tsx
  src/app/wines/[wineId]/components/flavorAnalysis/FlavorAnalysis.tsx
  src/app/wines/[wineId]/page.tsx
  src/components/Badge/Badge.tsx
  src/components/InputRange.tsx
  src/components/RangeSlider.tsx
Labels: 🧩 feature, 🛠️ refactor

#118 Feat/111 Myprofile 페이지 API 연동
  src/app/api/users/me/reviews/route.ts
  src/app/api/users/me/wines/route.ts
  src/app/design-system/ui-wine-list-card/page.tsx
  src/app/layout.tsx
  src/app/myprofile/(tab)/favorites/components/FavoriteContent.tsx
  src/app/myprofile/(tab)/favorites/components/SkeletionFavorite.tsx
  src/app/myprofile/(tab)/favorites/page.tsx
  src/app/myprofile/(tab)/reviews/page.tsx
  src/app/myprofile/(tab)/wines/page.tsx
  src/app/myprofile/components/Card/ReviewCard.tsx
  src/app/myprofile/components/Card/WineCard.tsx
  src/app/myprofile/components/LoadMoreBtn.tsx
  src/app/myprofile/components/Nothing.tsx
  src/app/myprofile/components/ProfileSection/ProfileSection.tsx
  src/app/myprofile/components/mock/mock-data.ts
  src/app/myprofile/components/mock/profile1.png
  src/app/myprofile/components/mock/wine-dummy.png
  src/app/myprofile/layout.tsx
  src/app/myprofile/types.ts
Labels: 📮 api

#139 next config 설정추가
  next.config.ts
Labels: 💬 chore

#130 이번 달 추천 와인 api 연결 & 스크롤 애니메이션
  src/app/design-system/ui-wine-list-card/page.tsx
  src/app/globals.css
  src/app/wines/components/RecommendedWineItem.tsx
  src/app/wines/components/WineRecommendationSection.tsx
  src/app/wines/types.ts
  src/hooks/useDeviceSize.ts
Labels: 📮 api, 🎨 design, 🧩 feature

#149 Feat/144 드롭다운 이벤트 전파 이슈
  src/components/Dropdown/Dropdown.Item.tsx
  src/components/Dropdown/Dropdown.Trigger.tsx
Labels: 🐞 bug

#152 [#150] refactor: qa사항 수정
  next.config.ts
  src/app/login/components/LoginForm.tsx
  src/app/signup/components/SignupForm.tsx
  src/components/Header.tsx
  src/middleware.ts
Labels: 🛠️ refactor

#151 [#135] feat: 스켈레톤 UI 구현
  src/app/design-system/page.tsx
  src/app/design-system/ui-skeleton/page.tsx
  src/app/wines/[wineId]/components/ReviewRating/ReviewRangeGroup.tsx
  src/app/wines/[wineId]/components/SkeletonUi/AromaAnalysisSkeleton.tsx
  src/app/wines/[wineId]/components/SkeletonUi/FlavorAnalysisSkeleton.tsx
  src/app/wines/[wineId]/components/SkeletonUi/ReviewCardSkeleton.tsx
  src/app/wines/[wineId]/components/SkeletonUi/ReviewOverviewSkeleton.tsx
  src/app/wines/[wineId]/components/SkeletonUi/WineCardSkeleton.tsx
  src/app/wines/[wineId]/components/SkeletonUi/WinePageSkeleton.tsx
  src/app/wines/[wineId]/page.tsx
Labels: 🎨 design

#155 6/18 멘토링 QA 반영
  src/app/wines/components/WineSearchSection.tsx
  src/components/Modal/ModalContent.tsx
Labels: 🐞 bug, 🛠️ refactor

#160 Feat/158 마이프로필 페이지 더보기 이슈
  src/app/myprofile/components/LoadMoreBtn.tsx
Labels: 🐞 bug

#156 Feat/143 6.18 멘토링 피드백 사항 수정
  src/apis/privateServerInstance.ts
  src/app/api/action/wine-action.ts
  src/app/myprofile/action/user-action.ts
  src/app/myprofile/components/ProfileChangeModal/ProfileChangeModal.tsx
  src/app/myprofile/components/ProfileSection.tsx
  src/components/Modals/WineModal/WineForm.tsx
  src/components/Modals/WineModal/WineModal.tsx
  src/constants/fileValidation.ts
Labels: 🐞 bug, 🛠️ refactor

#162 Feat/159 PWA적용
  eslint.config.mjs
  next.config.ts
  package.json
  pnpm-lock.yaml
  public/192x192.png
  public/384x384.png
  public/512x512.png
  public/manifest.json
  public/sw.js
  public/workbox-3c9d0171.js
  src/app/layout.tsx
Labels: 🧩 feature

#178 아이폰 사파리에서 모달창의 크기가 제대로 작동하지 않는 오류 해결
  src/components/Modal/ModalContent.tsx
Labels: 🐞 bug

#153 추천 와인 api 재연결
  src/app/api/wines/revalidate-recommended-wines/route.ts
  src/app/wines/components/WineRecommendationSection.tsx
  src/stores/dummy
  src/stores/recommendedWines.ts
Labels: 📮 api

#176 [#171] feat: 좋아요 낙관적 UI 와 디바운스 설정
  src/app/wines/[wineId]/components/ReviewCard.tsx
Labels: 🧩 feature

#179 [#173] feat: shadcn 토스트 메시지 추가
  components.json
  package.json
  pnpm-lock.yaml
  src/app/design-system/page.tsx
  src/app/design-system/ui-icon/page.tsx
  src/app/design-system/ui-toast/page.tsx
  src/app/globals.css
  src/app/layout.tsx
  src/app/wines/[wineId]/components/AromaAnalysis/AromaIcon.tsx
  src/app/wines/[wineId]/components/AromaAnalysis/types.ts
  src/app/wines/[wineId]/components/AromaAnalysis/utils.ts
  src/app/wines/[wineId]/dummy.ts
  src/app/wines/[wineId]/page.tsx
  src/components/ui/sonner.tsx
  src/lib/utils.ts
Labels: 🧩 feature

#174 Refactor/172
  src/actions/review.ts
  src/actions/wine.ts
  src/app/myprofile/components/Card/CardDropdown.tsx
  src/app/myprofile/components/Card/ReviewCard.tsx
  src/app/myprofile/components/Card/WineCard.tsx
  src/app/page.tsx
  src/app/wines/[wineId]/components/Nothing.tsx
  src/app/wines/[wineId]/components/ReviewCard.tsx
  src/app/wines/[wineId]/components/ReviewRating/ReviewOverview.tsx
  src/app/wines/[wineId]/components/ReviewRating/ReviewRatingButton.tsx
  src/app/wines/[wineId]/page.tsx
  src/components/ConfirmDeleteModal.tsx
  src/components/InputRange.tsx
  src/components/InputTextArea.tsx
  src/components/Modals/ReviewModal/ReviewModal.tsx
  src/components/RangeSlider.tsx
  src/components/StarRating.tsx
Labels: 🛠️ refactor

#186 Feat/181 Myprofile 페이지 ReviewCardDropdown 추가 및 ReviewCard수정
  public/sw.js
  src/app/(with-header)/myprofile/(tab)/reviews/page.tsx
  src/app/(with-header)/myprofile/components/Card/ReviewCard.tsx
  src/app/(with-header)/myprofile/components/Card/ReviewCardDropdown.tsx
  src/app/(with-header)/myprofile/components/Card/WineCard.tsx
  src/app/(with-header)/myprofile/components/Card/WineCardDropdown.tsx
  src/app/(with-header)/myprofile/components/LoadMoreBtn.tsx
Labels: 🛠️ refactor

#191 Feat/183 Wine 모달 & 프로필 변경 모달 토스트 메세지 적용
  src/app/(with-header)/myprofile/components/ProfileChangeModal/ProfileChangeModal.tsx
  src/components/Modals/WineModal/WineModal.tsx
Labels: 🎨 design, 🧩 feature

#193 Refactor/184 와인 상세페이지 와인 수정 시 바로 반영되도록 수정
  src/components/Modals/WineModal/WineModal.tsx
Labels: 🛠️ refactor

#192 [#185] 로그인/회원가입 페이지 토스트추가/UI수정
  src/app/(non-header)/login/components/LoginForm.tsx
  src/app/(non-header)/oauth/kakao/page.tsx
  src/app/(non-header)/signup/components/SignupForm.tsx
  src/components/Header.tsx
Labels: 🎨 design

#197 빌드 오류 해결 (누락된 타입, prop 추가)
  src/app/(with-header)/myprofile/components/Card/ReviewCard.tsx
  src/app/(with-header)/myprofile/components/LoadMoreBtn.tsx
Labels: 🐞 bug

#203 와인 목록 페이지 QA 반영
  src/app/(with-header)/wines/components/WineFilterSidebar.tsx
  src/app/globals.css
Labels: 🐞 bug

#206 Refactor/199 4차 QA 피드백 반영
  src/app/(with-header)/myprofile/action/user-action.ts
  src/app/(with-header)/myprofile/components/CardModal.tsx
  src/app/(with-header)/myprofile/components/ProfileChangeModal/ProfileChangeForm.tsx
  src/app/(with-header)/myprofile/components/ProfileChangeModal/ProfileChangeModal.tsx
  src/app/(with-header)/myprofile/components/ProfileSection.tsx
  src/app/(with-header)/wines/[wineId]/components/ReviewCard.tsx
  src/components/Modal/ModalContent.tsx
  src/components/Modals/WineModal/WineForm.tsx
  src/components/Modals/WineModal/WineModal.tsx
Labels: 🛠️ refactor

#202 [#198] QA사항 수정
  src/app/(non-header)/login/components/LoginForm.tsx
  src/app/(non-header)/signup/components/SignupForm.tsx
  src/components/Button.tsx
  src/constants/button.js
  src/utils/validateInput.ts
Labels: 🛠️ refactor

#205 [#201] refactor: 최종 QA반영
  src/components/InputRange.tsx
  src/components/InputTextArea.tsx
  src/components/Modals/ReviewModal/ReviewModal.tsx
Labels: 🛠️ refactor

#211 Refactor/209 목록 페이지 와인 크기 수정
  src/app/(with-header)/myprofile/components/LoadMoreBtn.tsx
  src/app/(with-header)/wines/components/WineListCard.tsx
  src/components/Modals/WineModal/WineForm.tsx
  src/components/WineInfo.tsx
Labels: 🎨 design, 🛠️ refactor

#215 랜딩 페이지에서 목록 페이지로 이동하는 버튼 추가
  src/app/assets/icons/desgin.tsx
  src/app/assets/icons/home.tsx
  src/app/page.tsx
Labels: 🧩 feature

#220 [#219] fix: 버그 수정
  src/app/(with-header)/wines/[wineId]/page.tsx
Labels: 🐞 bug

#227 [#222] docs: 리드미 작성
  README.md
  public/dog1.png
  public/dog2.png
  public/dog3.png
  public/dog4.png
  public/dog5.png
Labels: 📄 docs

#230 revalidateTag로 캐싱 무효화가 되지 않는 오류 해결
  src/app/api/wines/revalidate-recommended-wines/route.ts
Labels: 🐞 bug
